spring:
  application:
    name: boor-thymeleaf

  # JDBC 설정
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: springboot
    password: java1234


  # 강력 새로고침 되도록 만드는.. (개발할때는 캐시를 꺼놓음 false로)
  thymeleaf:
    cache: false

server:
  port: 8090

mybatis:
  mapper-locations: classpath:/mapper/*.xml
